const genBtn = document.querySelector('#genBtn');
const output = document.querySelector('#output');
const spin = document.querySelector('#spin');
const downloadBtn = document.querySelector('#downloadBtn');
//function that generates Qr code on click

genBtn.addEventListener('click', (e) => {
  e.preventDefault();
  clearUI();
  genBtn.setAttribute('disabled', '');
  setTimeout(() => {
    genBtn.removeAttribute('disabled');
  }, 1500);
  //Get everything we need
  const input = document.querySelector('#input').value;
  const size = document.querySelector('#qrSize').value;
  const label = document.querySelector('#label');
  const canvas = document.querySelector('#canvas');
  let lightColor = document.querySelector('#lightColor').value;
  let darkColor = document.querySelector('#darkColor').value;
  //function start
  if (input === '') {
    return (label.innerHTML = 'this field is required');
  } else {
    showElem(spin);
    setTimeout(() => {
      QRCode.toCanvas(canvas, input, { width: size, color: { light: lightColor, dark: darkColor } }, function (error) {
        if (error) console.error(error);
        console.log('success!');
      });
      hideElem(spin);
      setTimeout(() => {
        // Get save url
        let dataURL = canvas.toDataURL('image/png');
        // Create save button
        createSaveBtn(dataURL);
      }, 50);
    }, 1000);

    console.log('qr code should be generated by now');
  }
});
//function for downloading generated img
// Create save button to download QR code as image
const createSaveBtn = (saveUrl) => {
  const link = document.createElement('a');
  link.id = 'save-link';
  link.classList =
    'bg-green-100 hover:bg-white text-green-800 rounded-full py-3 px-8 shadow-md hover:shadow-2xl transition duration-500';
  link.href = saveUrl;
  link.download = 'qrcode';
  link.innerHTML = 'Save Image';
  document.getElementById('dwn').appendChild(link);
};
//helper functions
const clearUI = () => {
  //  output.innerHTML = '';
  const saveBtn = document.getElementById('save-link');
  if (saveBtn) {
    saveBtn.remove();
  }
};
showElem = (elem) => {
  elem.classList.remove('hidden');
};
hideElem = (elem) => {
  elem.classList.add('hidden');
};

//mobile menu button
const menuButton = document.querySelector('#menu-button');
const menu = document.querySelector('#menu');

menuButton.addEventListener('click', () => {
  menu.classList.toggle('hidden');
});
